<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE workflow [
<!ELEMENT workflow (transformation | analysis | generation)>
<!ELEMENT analysis (yes,no)>
<!ELEMENT yes (transformation | analysis | generation | errorstate)>
<!ELEMENT no (transformation | analysis | generation | errorstate)>
<!ELEMENT transformation (list,(transformation | analysis | generation | errorstate))>
<!ELEMENT list (file+)>
<!ELEMENT file EMPTY>
<!ATTLIST file path CDATA #REQUIRED>
<!ELEMENT generation EMPTY>
<!ELEMENT errorstate EMPTY>
<!ATTLIST analysis method CDATA #REQUIRED
                   mode CDATA #IMPLIED>
<!ATTLIST errorstate type CDATA #IMPLIED>
]>
<workflow>
    <transformation>
        <list>
            <file path="targets/arinc653_TT/CreateSchedulerEntities.asm" />
            <file path="targets/arinc653_TT/ExpandDelayedConnections.asm" />
        </list>
        <transformation>
            <list>
                <file path="targets/arinc653/ExpandThreadsPorts.asm" />
                <file path="ExpandSubprogramCalls.asm" />
                <file path="targets/arinc653/ExpandThreadsDispatchProtocol.asm" />
                <file path="CreateThreadsBehavior.asm" />
            </list>
            <generation />
        </transformation>
    </transformation>
</workflow>
